In [1]:
import src.classes.grid as grd

### Load grid from pylovo save file

In [2]:
### Run Settings
settings = {
    "grid_filename": "N2775500E4431500_86154_1_-6.h5",     # Name of input file
    # "grid_filename" = "N2827500E4503500_93426_5_41.h5",     
    "weather_data_exists": True,                           # Is weather data already included in input grid file's raw data? (recommended, as on HPC cluster no outside API access)
    "parallel": True,                                      # Parallelized run?
    "n_cpu": 12                                            # cpus if parallel 
}                    

# Setup grid which stores all relevant data for assigning demands
GRD = grd.Grid(settings)
GRD.df_buildings = GRD.df_buildings.iloc[0:10].reset_index(drop=True)

### Data and Demand Generation

Order of operations is important: Weather -> Solar -> Electricity -> Heat -> Mobility

##### Weather

In [3]:
GRD.retrieve_weather()
GRD.df_weather_raw.head()

,time(UTC),temp_air,relative_humidity,ghi,dni,dhi,IR(h),wind_speed,wind_direction,pressure,time(UTC+1),time(inst),dew_point,soil_temp
0,2009-12-31 23:00:00+00:00,1.54,91.00,0.0,0.0,0.0,308.86,2.97,248.0,93810.0,2009-01-01 00:00:00+01:00,2009-01-01 00:10:46+01:00,0.232245,7.4
1,2009-01-01 00:00:00+00:00,1.10,90.53,0.0,0.0,0.0,304.40,2.79,184.0,92720.0,2009-01-01 01:00:00+01:00,2009-01-01 01:10:46+01:00,-0.274091,7.4
2,2009-01-01 01:00:00+00:00,0.65,90.06,0.0,0.0,0.0,299.95,2.61,171.0,92670.0,2009-01-01 02:00:00+01:00,2009-01-01 02:10:46+01:00,-0.790121,7.4
3,2009-01-01 02:00:00+00:00,0.21,89.59,0.0,0.0,0.0,295.49,2.43,163.0,92610.0,2009-01-01 03:00:00+01:00,2009-01-01 03:10:46+01:00,-1.296080,7.4
4,2009-01-01 03:00:00+00:00,-0.24,89.12,0.0,0.0,0.0,291.04,2.25,163.0,92560.0,2009-01-01 04:00:00+01:00,2009-01-01 04:10:46+01:00,-1.811725,7.4

##### Solar data

In [4]:
GRD.generate_solar()
GRD.df_supim_solar.head()

            63                        64                     65          66  \
  solar_16_137 solar_16_317 solar_39_140 solar_39_320 solar_0_0 solar_62_10
t
0          0.0          0.0          0.0          0.0       0.0         0.0
1          0.0          0.0          0.0          0.0       0.0         0.0
2          0.0          0.0          0.0          0.0       0.0         0.0
3          0.0          0.0          0.0          0.0       0.0         0.0
4          0.0          0.0          0.0          0.0       0.0         0.0

                        67                        68                     69  \
  solar_62_190 solar_28_90 solar_28_270 solar_64_146 solar_64_326 solar_0_0
t
0          0.0         0.0          0.0          0.0          0.0       0.0
1          0.0         0.0          0.0          0.0          0.0       0.0
2          0.0         0.0          0.0          0.0          0.0       0.0
3          0.0         0.0          0.0          0.0          0.0       0.0
4          0.0         0.0          0.0          0.0          0.0       0.0

         70          71                     72
  solar_0_0 solar_52_39 solar_52_219 solar_0_0
t
0       0.0         0.0          0.0       0.0
1       0.0         0.0          0.0       0.0
2       0.0         0.0          0.0       0.0
3       0.0         0.0          0.0       0.0
4       0.0         0.0          0.0       0.0

##### Electricity

In [5]:
# Assign demand by statistics + predefined elec profiles
GRD.generate_electricity()
GRD.df_demand_elec.head()

,63,64,65,66,67,68,69,70,71,72
,electricity,electricity,electricity,electricity,electricity,electricity,electricity,electricity,electricity,electricity
0,0.171516,2.633075,0.622262,0.201958,0.159450,0.368840,0.436001,0.214751,0.337135,1.140414
1,0.182546,3.166620,0.434836,0.201187,0.165094,0.281464,0.295416,0.189297,0.595037,0.484815
2,0.167744,2.415608,0.442317,0.260790,0.309660,0.211655,0.156681,0.283516,0.546036,0.344447
3,0.191991,1.918031,0.476525,0.219319,0.286230,0.215159,0.136147,0.267228,0.169367,1.540231
4,0.209853,0.947024,0.524715,0.234049,0.235402,0.327859,0.254291,0.234461,0.142158,0.909711

##### Heat

In [6]:
GRD.generate_heat()
GRD.df_demand_heat_space.head()

,63,64,65,66,67,68,69,70,71,72
,space_heat,space_heat,space_heat,space_heat,space_heat,space_heat,space_heat,space_heat,space_heat,space_heat
0,10.501137,9.566118,9.730999,9.520451,9.759640,9.256703,8.681928,8.755982,8.940392,10.753584
1,11.685786,10.554669,10.861632,10.596162,10.431250,9.903093,9.686191,9.749395,9.520566,11.214232
2,12.789143,11.674010,11.884496,11.584388,11.061349,10.526848,10.622781,10.652127,10.114208,11.578254
3,13.806715,12.696509,12.829000,12.516490,11.685358,11.118896,11.476496,11.505442,10.728678,11.659894
4,14.759163,13.750297,13.709617,13.380619,12.294306,11.678622,12.252637,12.307431,11.288138,12.104681

In [7]:
GRD.df_demand_heat_water.head()

,63,64,65,66,67,68,69,70,71,72
,water_heat,water_heat,water_heat,water_heat,water_heat,water_heat,water_heat,water_heat,water_heat,water_heat
0,0.348726,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.412577,0.0
1,0.000000,0.0,0.0,0.0,0.284874,0.0,0.0,0.000000,0.000000,0.0
2,0.510809,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0
3,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.324167,0.000000,0.0
4,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0

In [8]:
GRD.df_tve_hpcop.head()

,63,64,65,66,67,68,69,70,71,72
,heatpump_air,heatpump_air,heatpump_air,heatpump_air,heatpump_air,heatpump_air,heatpump_air,heatpump_air,heatpump_air,heatpump_air
0,3.421196,3.438743,3.971268,3.438743,3.438743,3.438743,3.438743,3.438743,3.414660,3.438743
1,3.392420,3.392420,3.930361,3.392420,3.378655,3.392420,3.392420,3.392420,3.392420,3.392420
2,3.327040,3.345845,3.888975,3.345845,3.345845,3.345845,3.345845,3.345845,3.345845,3.345845
3,3.301088,3.301088,3.848950,3.301088,3.301088,3.301088,3.301088,3.288410,3.301088,3.301088
4,3.256115,3.256115,3.808465,3.256115,3.256115,3.256115,3.256115,3.256115,3.256115,3.256115

##### Mobility

In [4]:
GRD.generate_mobility()
GRD.df_demand_mobility.head()

KeyError: 'occ_list'

In [10]:
GRD.df_tve_mobility

                    63                                  64                65  \
     charging_station0 charging_station1 charging_station0 charging_station0
0                    1                 1                 1                 1
1                    1                 1                 1                 1
2                    1                 1                 1                 1
3                    1                 1                 1                 1
4                    1                 1                 1                 1
...                ...               ...               ...               ...
8755                 1                 0                 1                 1
8756                 1                 0                 1                 1
8757                 1                 1                 1                 1
8758                 1                 1                 1                 1
8759                 1                 1                 1                 1

                    66                                  67                    \
     charging_station0 charging_station1 charging_station0 charging_station1
0                    1                 1                 1                 1
1                    1                 1                 1                 1
2                    1                 1                 1                 1
3                    1                 1                 1                 1
4                    1                 1                 1                 1
...                ...               ...               ...               ...
8755                 1                 1                 0                 1
8756                 1                 1                 0                 1
8757                 1                 1                 0                 1
8758                 1                 1                 1                 1
8759                 1                 1                 1                 1

                    68                69                70                71
     charging_station0 charging_station0 charging_station0 charging_station0
0                    1                 1                 1                 1
1                    1                 1                 1                 1
2                    1                 1                 1                 1
3                    1                 1                 1                 1
4                    1                 1                 1                 1
...                ...               ...               ...               ...
8755                 1                 1                 1                 1
8756                 1                 1                 1                 1
8757                 1                 1                 1                 1
8758                 1                 1                 1                 1
8759                 1                 1                 1                 1

[8760 rows x 12 columns]

In [11]:
GRD.battery_dict

{(63, 0): 68.0,
 (63, 1): 55.0,
 (64, 0): 70.0,
 (65, 0): 55.0,
 (66, 0): 98.0,
 (66, 1): 35.5,
 (67, 0): 50.0,
 (67, 1): 54.2,
 (68, 0): 95.0,
 (69, 0): 17.5,
 (70, 0): 55.0,
 (71, 0): 60.0}

### Urbs Output Creation

In [12]:
GRD.create_weather_urbs()
GRD.df_weather_urbs.head()

  ambient
     Tamb Irradiation
t
0    1.54         0.0
1    1.10         0.0
2    0.65         0.0
3    0.21         0.0
4   -0.24         0.0

In [13]:
GRD.create_supim()
GRD.df_supim.head()

            63                        64                     65          66  \
  solar_16_137 solar_16_317 solar_39_140 solar_39_320 solar_0_0 solar_62_10
t
0          0.0          0.0          0.0          0.0       0.0         0.0
1          0.0          0.0          0.0          0.0       0.0         0.0
2          0.0          0.0          0.0          0.0       0.0         0.0
3          0.0          0.0          0.0          0.0       0.0         0.0
4          0.0          0.0          0.0          0.0       0.0         0.0

                        67                        68                     69  \
  solar_62_190 solar_28_90 solar_28_270 solar_64_146 solar_64_326 solar_0_0
t
0          0.0         0.0          0.0          0.0          0.0       0.0
1          0.0         0.0          0.0          0.0          0.0       0.0
2          0.0         0.0          0.0          0.0          0.0       0.0
3          0.0         0.0          0.0          0.0          0.0       0.0
4          0.0         0.0          0.0          0.0          0.0       0.0

         70          71                     72
  solar_0_0 solar_52_39 solar_52_219 solar_0_0
t
0       0.0         0.0          0.0       0.0
1       0.0         0.0          0.0       0.0
2       0.0         0.0          0.0       0.0
3       0.0         0.0          0.0       0.0
4       0.0         0.0          0.0       0.0

In [14]:
GRD.create_demand()
GRD.df_demand.head()

           63          64          65          66          67          68  \
  electricity electricity electricity electricity electricity electricity
t
0    0.171516    2.633075    0.622262    0.201958    0.159450    0.368840
1    0.182546    3.166620    0.434836    0.201187    0.165094    0.281464
2    0.167744    2.415608    0.442317    0.260790    0.309660    0.211655
3    0.191991    1.918031    0.476525    0.219319    0.286230    0.215159
4    0.209853    0.947024    0.524715    0.234049    0.235402    0.327859

           69          70          71          72  ...        64        65  \
  electricity electricity electricity electricity  ... mobility0 mobility0
t                                                  ...
0    0.436001    0.214751    0.337135    1.140414  ...       0.0       0.0
1    0.295416    0.189297    0.595037    0.484815  ...       0.0       0.0
2    0.156681    0.283516    0.546036    0.344447  ...       0.0       0.0
3    0.136147    0.267228    0.169367    1.540231  ...       0.0       0.0
4    0.254291    0.234461    0.142158    0.909711  ...       0.0       0.0

         66                  67                  68        69        70  \
  mobility0 mobility1 mobility0 mobility1 mobility0 mobility0 mobility0
t
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0

         71
  mobility0
t
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0

[5 rows x 42 columns]

In [15]:
GRD.create_tve()
GRD.df_tve.head()

            63           64           65           66           67  \
  heatpump_air heatpump_air heatpump_air heatpump_air heatpump_air
t
0     3.421196     3.438743     3.971268     3.438743     3.438743
1     3.392420     3.392420     3.930361     3.392420     3.378655
2     3.327040     3.345845     3.888975     3.345845     3.345845
3     3.301088     3.301088     3.848950     3.301088     3.301088
4     3.256115     3.256115     3.808465     3.256115     3.256115

            68           69           70           71           72  ...  \
  heatpump_air heatpump_air heatpump_air heatpump_air heatpump_air  ...
t                                                                   ...
0     3.438743     3.438743     3.438743     3.414660     3.438743  ...
1     3.392420     3.392420     3.392420     3.392420     3.392420  ...
2     3.345845     3.345845     3.345845     3.345845     3.345845  ...
3     3.301088     3.301088     3.288410     3.301088     3.301088  ...
4     3.256115     3.256115     3.256115     3.256115     3.256115  ...

                 64                65                66                    \
  charging_station0 charging_station0 charging_station0 charging_station1
t
0                 1                 1                 1                 1
1                 1                 1                 1                 1
2                 1                 1                 1                 1
3                 1                 1                 1                 1
4                 1                 1                 1                 1

                 67                                  68                69  \
  charging_station0 charging_station1 charging_station0 charging_station0
t
0                 1                 1                 1                 1
1                 1                 1                 1                 1
2                 1                 1                 1                 1
3                 1                 1                 1                 1
4                 1                 1                 1                 1

                 70                71
  charging_station0 charging_station0
t
0                 1                 1
1                 1                 1
2                 1                 1
3                 1                 1
4                 1                 1

[5 rows x 22 columns]

In [16]:
GRD.create_bsp()
GRD.df_bsp.head()

   electricity_import  electricity_feed_in
t
0               0.398               0.0562
1               0.398               0.0562
2               0.398               0.0562
3               0.398               0.0562
4               0.398               0.0562

In [17]:
GRD.create_processes()
GRD.df_pro.head()

,Site,Process,inst-cap,cap-up,inv-cost-fix,inv-cost,fix-cost,var-cost,wacc,depreciation,pf-min
0,63,import,2000,2000.0,NaN,0.0,0,0,0.07,30,NaN
1,64,import,2000,2000.0,NaN,0.0,0,0,0.07,30,NaN
2,65,import,2000,2000.0,NaN,0.0,0,0,0.07,30,NaN
3,66,import,2000,2000.0,NaN,0.0,0,0,0.07,30,NaN
4,67,import,2000,2000.0,NaN,0.0,0,0,0.07,30,NaN

In [18]:
GRD.create_commodities()
GRD.df_com.head()

   Site    Commodity    Type  price
0    63  electricity  Demand    NaN
1    64  electricity  Demand    NaN
2    65  electricity  Demand    NaN
3    66  electricity  Demand    NaN
4    67  electricity  Demand    NaN

In [19]:
GRD.create_process_commodity()
GRD.df_pro_com.head()

            Process            Commodity Direction  ratio
0            import   electricity_import        In      1
1            import          electricity       Out      1
2           feed_in          electricity        In      1
3           feed_in  electricity_feed_in       Out      1
4  Heat_dummy_space          common_heat        In      1

In [20]:
GRD.create_storages()
GRD.df_sto.head()

,Site,Storage,Commodity,inst-cap-c,cap-up-c,inst-cap-p,cap-up-p,eff-in,eff-out,discharge,ep-ratio,inv-cost-p,inv-cost-c,fix-cost-p,fix-cost-c,var-cost-p,wacc,depreciation
0,63,battery_private,electricity,0.0,6000.0,0.0,2000.0,0.961,1,0,1.58,0,976,0,0,0.001,0.022,15
1,64,battery_private,electricity,0.0,6000.0,0.0,2000.0,0.961,1,0,1.58,0,976,0,0,0.001,0.022,15
2,65,battery_private,electricity,0.0,6000.0,0.0,2000.0,0.961,1,0,1.58,0,976,0,0,0.001,0.022,15
3,66,battery_private,electricity,0.0,6000.0,0.0,2000.0,0.961,1,0,1.58,0,976,0,0,0.001,0.022,15
4,67,battery_private,electricity,0.0,6000.0,0.0,2000.0,0.961,1,0,1.58,0,976,0,0,0.001,0.022,15

### Saving Grid Data

In [21]:
df = GRD.save_grid_data()